version: '2'
services:
  hks:
    restart: always
    build:
      context: ./
      dockerfile: Dockerfile
    # image: php:alpine
    volumes:
      - ./:/var/www/html
    ports:
      - "9000"
    links:
      - redis
      - mysql
    environment:
      - VIRTUAL_HOST=hks.jianxun.io
      - VIRTUAL_ROOT=/var/www/html
    command: ["php", "-S", "0.0.0.0:9000", "-t", "/var/www/html/public", "/var/www/html/server.php"]

  redis:
    restart: always
    image: redis:alpine

  mysql:
    restart: always
    image: mysql:5.7
    ports:
      - "0.0.0.0:33064:3306"
    volumes:
      - ./data/mysql/data:/var/lib/mysql
      - ./data/mysql/conf.d:/etc/mysql/conf.d
    environment:
      MYSQL_ROOT_PASSWORD: 'huntcoder2018'
      TZ: 'Asia/Shanghai'

  proxy:
    image: jwilder/nginx-proxy:alpine
    ports:
      - "8082:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro



